$file = "c:\Users\Admin\Downloads\Cầu Vồng_BACKUP\12\src\components\AdminDashboard.tsx"
$content = [System.IO.File]::ReadAllText($file)

$old = "                                               <td className=""p-2 text-center pr-4"">`r`n                                                 {firstAtt && (`r`n                                                   <div className=""flex items-center justify-center gap-2"">`r`n                                                     {atts?.every((a:any) => a.confirmedByAdmin) ? (`r`n                                                       <span className=""text-[9px] text-emerald-700 font-bold border border-emerald-200 bg-emerald-50 px-2 py-1 rounded-full"">`r`n                                                         ĐÃ DUYỆT`r`n                                                       </span>`r`n                                                     ) : (`r`n                                                       <button `r`n                                                         onClick={(e) => { e.stopPropagation(); handleApproveAttendance(atts!.map((a:any) => a.id)); }}`r`n                                                         className={``text-[9px] font-bold px-2 py-1.5 rounded text-white transition `${isFlagged ? 'bg-red-600 hover:bg-red-700' : 'bg-blue-600 hover:bg-blue-700'}``}`r`n                                                       >`r`n                                                         Duyệt`r`n                                                       </button>`r`n                                                     )}`r`n                                                   </div>`r`n                                                 )}`r`n                                               </td>"

$new = "                                               <td className=""p-2 text-center pr-4"">`r`n                                                 <div className=""flex items-center justify-center gap-2"">`r`n                                                   {!firstAtt ? (`r`n                                                     <button`r`n                                                       onClick={(e) => {`r`n                                                         e.stopPropagation();`r`n                                                         const schIds = schs ? schs.map((s:any) => s.id) : [];`r`n                                                         const clsIds = schs ? schs.map((s:any) => s.classId) : [];`r`n                                                         const sId = schs ? schs[0].schoolId : '';`r`n                                                         const sess = schs ? schs[0].session : '';`r`n                                                         setManualAttModal({ teacherId: teacher.id, scheduleIds: schIds, date: attendanceDate, session: sess, schoolId: sId, classIds: clsIds });`r`n                                                       }}`r`n                                                       className=""text-[9px] font-bold px-2 py-1.5 rounded text-white bg-purple-600 hover:bg-purple-700 transition""`r`n                                                     >`r`n                                                       + Nhập thủ công`r`n                                                     </button>`r`n                                                   ) : atts?.every((a:any) => a.confirmedByAdmin) ? (`r`n                                                     <span className=""text-[9px] text-emerald-700 font-bold border border-emerald-200 bg-emerald-50 px-2 py-1 rounded-full"">`r`n                                                       ĐÃ DUYỆT`r`n                                                     </span>`r`n                                                   ) : (`r`n                                                     <button `r`n                                                       onClick={(e) => { e.stopPropagation(); handleApproveAttendance(atts!.map((a:any) => a.id)); }}`r`n                                                       className={``text-[9px] font-bold px-2 py-1.5 rounded text-white transition `${isFlagged ? 'bg-red-600 hover:bg-red-700' : 'bg-blue-600 hover:bg-blue-700'}``}`r`n                                                     >`r`n                                                       Duyệt`r`n                                                     </button>`r`n                                                   )}`r`n                                                 </div>`r`n                                               </td>"

if ($content.Contains($old)) {
  $newContent = $content.Replace($old, $new)
  [System.IO.File]::WriteAllText($file, $newContent, [System.Text.Encoding]::UTF8)
  Write-Host "SUCCESS: Replacement done!"
} else {
  Write-Host "NOT FOUND - showing relevant section..."
  # Show lines 3279-3298 raw
  $lines = $content -split "`r`n"
  for ($i=3279; $i -le 3298; $i++) { Write-Host "[$i]: $($lines[$i])" }
}
